version: '3.3'
services:
  fava:
    build: .
    container_name: fava
    environment:
      BEANCOUNT_FILE: /input.beancount
      TZ: Asia/Bangkok
    ports:
      - '5004:5000'
    volumes:
      - /Users/kahnwong/Git/budget/beans.beancount:/input.beancount
    restart: unless-stopped
