[project]
name = "ci-playground"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Karn Wong", email = "karn@karnwong.me" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.33.1",
]

[project.scripts]
ci-playground = "ci_playground:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
# [tool.uv.build-backend]
# module-root = "api"

# [tool.uv]
# package = false
