name: Select elem from output array

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=raw,value={{sha}}
            # type=raw,value=latest
      - name: Print value
        run: |
          echo ${{ steps.meta.outputs.tags }} | jq

      # - name: Select sha image tag
      #   run: |
      #     echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      # - name: Test
      #   run: echo $GITHUB_SHA_SHORT
